routes:
    /archivo/:
        controller: channel
        template: archivo

    /glosario/:
        data: page.glosario
        template: glosario

collections:
    /:
        permalink: /{slug}/
        template: index

taxonomies:
    tag: /etiqueta/{slug}/
